name: Build and run unit tests
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'examples'

concurrency:
  group: test-${{ github.ref }}
permissions:
  contents: read
jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     timeout-minutes: 5
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Install go
#         uses: actions/setup-go@v4
#         with:
#           go-version-file: 'go.mod'
#           cache: true

#       - name: Install deps
#         run: go mod download

#       - name: Build
#         run: go build -v .

  test:
    name: Terraform Provider Acceptance Test
    # needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.*
          terraform_wrapper: false

      - name: Install deps
        run: go mod download

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Test
        env:
          TF_ACC: 1
          API_TOKEN: ${{ secrets.API_TOKEN_DEV_INTERNAL_TEST_TENANT }}
          PLATFORM_URL: 'https://api-dev.traceable.ai'
        run: gotestsum --format standard-verbose --junitfile unit-test-report.xml -- -cover ./internal/resources/
        timeout-minutes: 6

      - name: Upload test report
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: unit-test-report.xml
          retention-days: 7